# Base configuration - common settings for all environments
spring:
  application:
    name: weather-api-service
  profiles:
    active: local  # Default to local environment

# Common server configuration
server:
  port: 8080

# Common cache TTL configuration
cache:
  ttl:
    weathers-current: 15m
    weathers-forecast: 12h
    weathers-historical: 7d

# Common weather API configuration
weather:
  api:
    base-url: https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline
    key: YOUR_API_KEY_HERE  # Replace with your actual API key or use environment variable
    connect-timeout: 3s
    read-timeout: 5s

# Common management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true