spring:
  application:
    name: weather-api-service
  data:
    redis:
      host: localhost
      port: 6379

  devtools:
    restart:
      enabled: false

server:
  port: 8081

cache:
  ttl:
    weathers-current: 15m
    weathers-forecast: 12h
    weathers-historical: 7d

weather:
  api:
    base-url: https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline
    key: T9FM85UY3S5VGQWPGKZYQL5UR
    connect-timeout: 3s
    read-timeout: 5s

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always