# Production environment configuration
spring:
  data:
    redis:
      host: ${REDIS_HOST:redis-cluster.example.com}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      password: ${REDIS_PASSWORD:}
      ssl: ${REDIS_SSL:false}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 32
          max-idle: 16
          min-idle: 4
          max-wait: 2000ms

  # Disable dev tools in production
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

# Production logging configuration
logging:
  level:
    root: WARN
    vn.ttg.roadmap.weatherapiservice: INFO
    org.springframework.cache: WARN
    org.springframework.data.redis: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}] - %msg%n"
  file:
    name: ${LOG_FILE_PATH:/var/log/weather-api-service/application.log}
    max-size: 500MB
    max-history: 30

# Production weather API settings
weather:
  api:
    key: ${WEATHER_API_KEY}
    connect-timeout: 2s
    read-timeout: 3s

# Production management endpoints (limited exposure)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
    info:
      enabled: true
    metrics:
      enabled: false

# Production-specific settings
app:
  environment: production
  debug: false

# Security settings for production
security:
  require-ssl: true
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
